### ISSUE TITLE
Font to display code has changed from 3.1.1 to 3.2.0 

### ISSUE THREAD

**Issue by line-o** [eXist-db/eXide#391]
In Safari the font used to display code was "Monaco" in eXide v3.1.1.
After an update to eXide v3.2.0 the effective font changed to ".SF NS Mono" (`ui-monospace` on my system).

As @plutonik-a pointed out the CSS rule that leads to this is 
```css
#editor { 
  font-family: ui-monospace, 'Ubuntu Mono', 'Monaco', 'Menlo', 'Droid Sans Mono', 'Courier New', monospace;
}
```

ui-monospace now takes precedence over "Monaco".

Screenshots:
v3.1.1
![Screenshot 2021-11-25 at 11 59 21](https://user-images.githubusercontent.com/657222/143446341-19e9b8a3-ab22-4b7c-bf9e-ac6a9b247b65.png)

v3.2.0
![Screenshot 2021-11-25 at 12 00 01](https://user-images.githubusercontent.com/657222/143446335-6840a409-c032-405d-8f93-eb5a819ef109.png)

I just wanted to bring this to attention. I am unsure if this change was intentional and would like to discuss what we think is best.
